name: shiroko

x-consumer-app: &consumer-app
  volumes:
    - .:/app
  networks: [ shiroko-net ]
  environment:
    TZ: $TZ
services:
  tts_splitter:
    <<: *consumer-app
    container_name: tts_splitter_consumer
    hostname: tts.splitter
    image: tts_splitter
    ports:
      - 9015:9015
    depends_on:
      queue:
        condition: service_healthy

        
    networks:
      - shiroko-net

    
  tts_consumer:
    <<: *consumer-app
    container_name: tts_consumer
    image: tts_consumer
    hostname: tts.consumer
    ports:
      - 9014:9014
    depends_on:
      tts_splitter:
        condition: service_started

      queue:
        condition: service_healthy
    # ports:
    #   - $DEBUGGER_PORT:$DEBUGGER_PORT

    networks:
      - shiroko-net

  rvc_consumer:
    <<: *consumer-app
    container_name: rvc_consumer
    hostname: rvc.consumer
    image: rvc_consumer
    ports:
      - 9016:9016
    depends_on:
      tts_consumer:
        condition: service_started
      rvc:
        condition: service_started
      queue:
        condition: service_healthy

    networks:
      - shiroko-net
  
  rvc:
    container_name: $RVC_HOST
    hostname: shiroko.rvc
    image: rvc-api
    build:
      context: .
    command: -p $RVC_PORT -pi 4
    ports:
      - $RVC_PORT:$RVC_PORT
    networks: [ shiroko-net ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  queue:
    container_name: $RABBITMQ_HOST
    hostname: shiroko.rabbit
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
      RABBITMQ_NODE_PORT: $RABBITMQ_PORT
    ports:
      - $RABBITMQ_PORT:$RABBITMQ_PORT
      - '15672:15672'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    networks: [shiroko-net]

  backend:
    container_name: shiroko-backend
    restart: always
    hostname: shiroko.backend
    build:
      target: backend
      context: .
    volumes:
      - .:/app
    ports:
      - $DEBUGGER_PORT:$DEBUGGER_PORT
      - $PORT:$PORT
    networks: [shiroko-net]
    environment:
      TZ: $TZ
    
    
    depends_on:
      - database
      - storage
      - rvc

  database:
    image: mongo
    hostname: shiroko.db
    container_name: $DB_HOST
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
      TZ: $TZ
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - mongo_volume:/data/db
    networks: [shiroko-net]
  storage:
    hostname: shiroko.minio
    image: minio/minio
    command: server /data --console-address ":$MINIO_WEBUI_PORT"
    container_name: $MINIO_HOST
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      TZ: $TZ
    networks:
      - shiroko-net
    volumes:
      - minio_volume:/data
    ports:
      - '9000:9000'
      - '9001:9001'
      

volumes:
  mongo_volume:
    name: shiroko_db
  minio_volume:
    name: shiroko_minio
  rabbitmq_volume:
    name: shiroko_rabbitmq
networks:
  shiroko-net:
    name: shiroko-net
